"""baseline

Revision ID: 3905cc81b383
Revises: 
Create Date: 2026-02-09 15:08:50.008321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3905cc81b383'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_follows_created_at'), 'follows', ['created_at'], unique=False)
    op.create_index(op.f('ix_follows_influencer_id'), 'follows', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_follows_user_id'), 'follows', ['user_id'], unique=False)
    op.add_column('influencer_assets', sa.Column('meta', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_influencer_assets_influencer_id'), 'influencer_assets', ['influencer_id'], unique=False)
    op.add_column('posts', sa.Column('mode', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('post_type', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('status', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('meta', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_influencer_id'), 'posts', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_posts_mode'), 'posts', ['mode'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index(op.f('ix_reactions_created_at'), 'reactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_reactions_post_id'), 'reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('onboarding_version', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('preferred_niches_json', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_styles_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_styles_json')
    op.drop_column('users', 'preferred_niches_json')
    op.drop_column('users', 'onboarding_version')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_count')
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_post_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_created_at'), table_name='reactions')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_mode'), table_name='posts')
    op.drop_index(op.f('ix_posts_influencer_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_column('posts', 'meta')
    op.drop_column('posts', 'status')
    op.drop_column('posts', 'post_type')
    op.drop_column('posts', 'mode')
    op.drop_index(op.f('ix_influencer_assets_influencer_id'), table_name='influencer_assets')
    op.drop_column('influencer_assets', 'meta')
    op.drop_index(op.f('ix_follows_user_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_influencer_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_created_at'), table_name='follows')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    # ### end Alembic commands ###
